### PR TITLE
Add more fields supported by People API.

### PR DESCRIPTION
**Pull request by felix-zaslavskiy**
This adds a few more fields that are supported by a typical Google (+) Profile. Useful things are Work and Education may be returned now from the People API.

### CODE REVIEW

**Comment by mlaccetti** [comment]
@felix-zaslavskiy Will this work, now that G+ is being sunset?

**Comment by felix-zaslavskiy** [comment]
> @felix-zaslavskiy Will this work, now that G+ is being sunset?
Should since I am updating the use of People API and there is no plans from google to change anything. Users google profile data should be accessible even with G+ going away.

**Comment by mlaccetti** [comment]
@felix-zaslavskiy can you fix the tests, then?

**Comment by felix-zaslavskiy** [comment]
> @felix-zaslavskiy can you fix the tests, then?

Fixed!

**Pull request merged**
